rmarkdown::render("phylogenize-report.Rmd",
  output_file = "phylogenize-output.html",
  params = list(out_dir = "./new-project/output",
    in_dir = "./new-project/input",
    type = "16S",
    db_version = "midas_v1.2",
    which_phenotype = "specificity",
    which_envir = "(environment)",
    abundance_file = "",
    metadata_file = "",
    biom_file = "new-project-data-and-metadata.biom",
    input_format = "biom",
		burst_dir = "./",
    ncl = 10))

