[workspace]
authors = ["Patrick Bradley <bradley.720@osu.edu>"]
channels = ["conda-forge", "bioconda"]
name = "phylogenize"
platforms = ["linux-64"]
version = "2.0-alpha"

[tasks]

[dependencies]
r-base = "*"
r-readr = "*"
r-dplyr = "*"
r-stringr = "*"
r-tidyr = "*"
r-tibble = "*"
r-purrr = "*"
r-matrix = "*"
r-ape = "*"
r-ashr = "*"
bioconductor-biomformat = "*"
r-castor = "*"
r-dt = "*"
r-extradistr = "*"
r-forcats = "*"
r-ggplot2 = "*"
bioconductor-ggtree = "*"
r-htmlwidgets = "*"
r-kableextra = "*"
r-knitr = "*"
r-mass = "*"
r-patchwork = "*"
r-pbapply = "*"
r-phylolm = "*"
r-plotly = "*"
bioconductor-qvalue = "*"
r-rlang = "*"
r-rmarkdown = "*"
r-scales = "*"
r-seqinr = "*"
r-settings = "*"
r-svglite = "*"
r-yaml = "*"
bioconductor-maaslin2 = "*"
r-devtools = "*"
ca-certificates = "*"
openssl = "*"
bioconductor-ancombc = "*"
"r-data.table" = "*"
r-phangorn = "*"
r-xnomial = "*"
bioconductor-clusterprofiler = "*"
vsearch = ">=2.30.0,<3"
