# Snakemake workflow to use kraken2 + bracken to calculate species-level
# abundances in the provided samples of paired-end reads.

# Invoke snakemake with --config datadir=<path_to_data>
# If not provided, input data files are assumed to exist in the current working # directory.
#
import re
fq = re.compile("(_\\d)?\\.f(ast)?q(\\.gz)?$")

try:
    exp_datadir = config["datadir"]
    datadir = exp_datadir
except(KeyError):
    exp_datadir = "."
    datadir = ""

# prune off pair and extension(s)
SAMPLES = [re.sub(fq, "", d) for d in os.listdir(exp_datadir) if re.search(fq, d)]

rule all:
    input:
        expand("abund/{sample}.bracken", sample=SAMPLES)


rule kraken:
    input: 
        in1 = os.path.join(datadir, "{sample}_1.fastq"),
        in2 = os.path.join(datadir, "{sample}_2.fastq"),
    output: 
        out = "abund/{sample}.kraken2",
        report = "abund/{sample}.kreport",
    resources:
        runtime = 10,
        mem_mb = "100000",
        nodes = 1,
    shell:
        "kraken2 --db /fs/project/bradley.720/db/uhgg2/kraken2_db_uhgg_v2.0.2/ "
        "--threads 40 "
        "--output {output.out} "
        "--report {output.report} "
        "--paired "
        "{input.in1} {input.in2} "


rule bracken:
    input: 
        "abund/{sample}.kreport",
    output: 
        "abund/{sample}.bracken",
    resources:
        runtime = 10,
        nodes = 1,
    shell:
        "bracken -d /fs/project/bradley.720/db/uhgg2/kraken2_db_uhgg_v2.0.2/ "
        "-i {input} "
        "-o {output} "
        "-r 100 "
        "-l R7"
