
#--- Process 16S data---#

resolve.16s.paths <- function(..., .opts=NULL) {
    opts <- pz.resolve.options(..., .opts=.opts)
    out_dir <- opts('out_dir')
    if (is.null(out_dir) || is.na(out_dir) || out_dir == "") {
        out_dir <- "."
    }
    path_or_default <- function(value, filename) {
        if (is.null(value) || is.na(value) || value == "") {
            file.path(out_dir, filename)
        } else {
            value
        }
    }
    updates <- list(
        named_asv_file=path_or_default(opts('named_asv_file'),
                                       "phylogenize-16s-asvs.fna"),
        vsearch_outfile=path_or_default(opts('vsearch_outfile'),
                                        "phylogenize-16s-vsearch.tsv"),
        audit_16s_file=path_or_default(opts('audit_16s_file'),
                                       "phylogenize-16s-assignments.tsv")
    )
    if (opts('which_16s_method') == "appspam") {
        updates$jplace_file <- path_or_default(opts('jplace_file'),
                                               "phylogenize-16s.jplace")
    }
    do.call(pz.resolve.options, c(list(.opts=opts), updates))
}

write.16s.audit <- function(audit, ..., .opts=NULL) {
    opts <- resolve.16s.paths(..., .opts=.opts)
    audit_file <- opts('audit_16s_file')
    if (is.null(audit_file) || is.na(audit_file) || audit_file == "") {
        return(invisible(FALSE))
    }
    ensure_parent_dir(audit_file, .opts=opts)
    readr::write_tsv(audit, audit_file)
    pz.message(paste0("  ..........16S assignment audit written to ",
                      audit_file),
               .opts=opts)
    invisible(TRUE)
}

#' Prepare input file for alignment
#'
#' \code{prepare.vsearch.input} outputs a FASTA file of the sequences in the
#' input 16S data for analysis using vsearch or vsearch.
#'
#' Some particularly relevant options are:
#' \describe{
#'   \item{named_asv_file}{String. File name of the sequences written to disk
#'   and then read into vsearch/vsearch.}
#' }
#'
#' @param mtx A presence/absence or abundance matrix, with row names equal to
#'   amplicon sequence variant DNA sequences.
#' @export
prepare.vsearch.input <- function(mtx, ..., .opts=NULL) {
    opts <- resolve.16s.paths(..., .opts=.opts)
    check.dna <- is.dna(rownames(mtx))
    if (!(all(check.dna))) {
        pz.error(paste0(
            "Rownames in 16S data must correspond to the actual sequences of ", 
            "denoised amplicon sequence variants, but some rownames contained ",
            "invalid characters ",
            "(e.g. ", rownames(mtx)[which(!check.dna)[1]], ")."),
            .opts=opts)
    }
    asvnames = paste0("Row", (1:nrow(mtx)))
    asvs = rownames(mtx)
    ensure_parent_dir(opts('named_asv_file'), .opts=opts)
    seqinr::write.fasta(as.list(asvs),
                        asvnames,
                        file.out=opts('named_asv_file'),
                        nbchar=99999,
                        as.string=TRUE)
    return(TRUE)
}

run.external.tool <- function(command,
                              args,
                              error_label,
                              ...,
                              .opts=NULL,
                              message_label=NULL) {
    opts <- pz.resolve.options(..., .opts=.opts)
    if (!is.null(message_label)) {
        pz.message(paste0("Calling ", message_label, " with arguments: ",
                          paste(args, sep=" ", collapse=" ")),
                   .opts=opts)
    }
    r <- system2(command, args=args)
    if (r != 0) {
        pz.error(paste0(error_label, " failed with error code ", r),
                 .opts=opts)
    }
    TRUE
}

#' Run vsearch analysis on a FASTA file of sequences.
#'
#' \code{run.vsearch} runs, by default, the optimal sequence aligner vsearch
#' (doi.org/10.5281/zenodo.806850) on a FASTA file, typically one generated by
#' \code{prepare.vsearch.input}. By changing the \code{vsearch_dir} option, the
#' aligner vsearch can also be used. If the provided binary name is
#' not"vsearch", \emph{phylogenize} will assume an old version of vsearch is
#' being called that doesn't have the ability to search both strands.
#'
#' Some particularly relevant options are:
#' \describe{
#'   \item{named_asv_file}{String. File name of the sequences to be read into
#' vsearch.}
#'   \item{vsearch_outfile}{String. File name where vsearch writes output
#'   which is then read back into \emph{phylogenize}.}
#'   \item{vsearch_dir}{String. Path where the binary of vsearch is found.}
#'   \item{vsearch_cutoff}{Float. Between 0.95 and 1.00; percent identity
#'   minimum for alignment results.}
#'   \item{vsearch_16sfile}{String. Path to the 16S FASTA database that maps
#'   back to MIDAS species.}
#'   \item{data_dir}{String. Path to directory containing the data files
#' required to perform a \emph{phylogenize} analysis. }
#' }
#'
#' @return Returns TRUE unless an error is thrown.
#' @export run.vsearch
run.vsearch <- function(..., .opts=NULL) {
    opts <- resolve.16s.paths(..., .opts=.opts)
    vsearch_path <- opts('vsearch_dir')
    if (dir.exists(vsearch_path)) {
        vsearch_path <- file.path(vsearch_path, "vsearch")
    }
    if (vsearch_path == "" || !(file.exists(vsearch_path))) {
        pz.error(paste0("vsearch executable not found: ", opts('vsearch_dir')),
                 .opts=opts)
    }
    if (file.access(vsearch_path, mode=1) != 0) {
        pz.error(paste0("vsearch executable is not runnable: ", vsearch_path),
                 .opts=opts)
    }
    query_file <- opts('named_asv_file')
    if (!(file.exists(query_file))) {
        pz.error(paste0("16S query FASTA not found: ", query_file),
                 .opts=opts)
    }
    db_file <- file.path(opts('data_dir'), opts('vsearch_16sfile'))
    if (!(file.exists(db_file))) {
        pz.error(paste0("16S reference FASTA not found: ", db_file),
                 .opts=opts)
    }
    pid <- suppressWarnings(as.numeric(opts('vsearch_cutoff')))
    if (is.na(pid) || pid <= 0 || pid > 1) {
        pz.error("vsearch_cutoff must be a number greater than 0 and at most 1",
                 .opts=opts)
    }
    binary <- basename(vsearch_path)
    ensure_parent_dir(opts('vsearch_outfile'), .opts=opts)
    vsearch_args <- c("--db",
			     db_file,
			     "--usearch_global",
			     query_file,
			     "--strand",
			     "both",
			     "--id",
			     pid,
			     "--maxaccepts",
		     20,
		     "--blast6out",
		     opts('vsearch_outfile'))
    run.external.tool(vsearch_path,
                      vsearch_args,
                      error_label="Aligner",
                      message_label=paste("aligner", binary),
                      .opts=opts)
}

#' Read in results from vsearch.
#'
#' \code{get.vsearch.results} reads and parses the output of vsearch to get the
#' best-hit MIDAS species identifier for any 16S hit. Note that the reference
#' 16S FASTA database file must describe entries in the format: ">gene;;
#' species_or_genus_ID;;MIDAS_ID". Only MIDAS_ID is used so the contents of
#' "gene" and "species_or_genus_ID" can be arbitrary.
#'
#' Some particularly relevant options are:
#' \describe{
#'   \item{vsearch_outfile}{String. File name where vsearch writes output
#'   which is then read back into \emph{phylogenize}.}
#' }
#'
#' @return List containing a vector of hits, a vector of MIDAS ID targets, and a
#'     data frame of the assignments as they came out of vsearch.
#' @export
get.vsearch.results <- function(..., .opts=NULL) {
    opts <- resolve.16s.paths(..., .opts=.opts)
    vf <- opts('vsearch_outfile')
    if (!(file.exists(vf))) {
        pz.error(paste0("vsearch output file not found: ", vf), .opts=opts)
    }
    if (file.info(vf)$size == 0) {
        pz.error(paste0("vsearch output file was empty: ", vf), .opts=opts)
    }
    # map to MIDAS IDs using vsearch (note X1 is query name, X3 is pctid)
    assignments <- 
        readr::read_tsv(vf, col_names=FALSE, show_col_types=FALSE)
    if (ncol(assignments) < 3) {
        pz.error("vsearch output must contain at least 3 tab-delimited columns",
                 .opts=opts)
    }
    if (nrow(assignments) == 0) {
        pz.error(paste0("vsearch output file had no assignments: ", vf),
                 .opts=opts)
    }
    pct_id <- suppressWarnings(as.numeric(assignments[[3]]))
    if (any(is.na(pct_id))) {
        pz.error("vsearch output contains nonnumeric percent identity values",
                 .opts=opts)
    }
    assignments[[3]] <- pct_id
    query_ok <- grepl("^Row[0-9]+$", assignments[[1]])
    if (any(!query_ok)) {
        pz.error(paste0(
            "vsearch output contains invalid query ID(s): ",
            paste(unique(assignments[[1]][!query_ok]), collapse=", ")
        ), .opts=opts)
    }
    target_parts <- strsplit(assignments[[2]], ";;", fixed=TRUE)
    target_ok <- vapply(target_parts, length, integer(1)) >= 3
    if (any(!target_ok)) {
        pz.error(paste0(
            "vsearch output contains malformed target ID(s): ",
            paste(unique(assignments[[2]][!target_ok]), collapse=", ")
        ), .opts=opts)
    }
    assignments <- assignments %>%
        dplyr::group_by(X1) %>%
        dplyr::slice_max(X3) %>%
	dplyr::ungroup()
    row.hits <- as.numeric(gsub("Row", "", assignments[[1]]))
    row.targets <- vapply(strsplit(assignments[[2]], ";;", fixed=TRUE),
                          function(x) x[[3]],
                          character(1))
    return(list(hits=row.hits, targets=row.targets, assn=assignments))
}

#' Sum non-unique rows after vsearch mapping.
#'
#' \code{sum.nonunique.vsearch} takes vsearch results and an abundance or
#' presence/absence matrix, drops any rows that mapped to multiple MIDAS IDs
#' (i.e. that couldn't confidently be assigned to a MIDAS species),
#' then sums any rows that mapped to the same MIDAS ID. An ASV is retained only
#' if exactly one MIDAS ID reaches \code{min_frac_16s}.
#'
#' Some particularly relevant options are:
#' \describe{
#'   \item{min_frac_16s}{Numeric. Should be between 0.5 and 1. Only keep ASVs
#'   where at least this fraction of assignments are to the same species. 
#'   Allows some tolerance for mislabeled or phylogenetically-inconsistent
#'   16S sequences in the database. Default: 0.8}
#'   \item{out_dir}{String. Path to output directory. Default: "output"}
#'   \item{data_dir}{String. Path to directory containing the data files
#'   required to perform a \emph{phylogenize} analysis. Default: on package
#'   load, this default is set to the result of \code{system.file("extdata",
#'   package="phylogenize")}.}
#' }
#'
#' @param vsearch A list obtained by running \code{get.vsearch.results}.
#' @param mtx A presence/absence or abundance matrix, with row names equal to
#'     amplicon sequence variant DNA sequences.
#' @return A new matrix with MIDAS IDs as rows.
#' @export sum.nonunique.vsearch
sum.nonunique.vsearch <- function(vsearch, mtx, ..., .opts=NULL) {
    opts <- pz.resolve.options(..., .opts=.opts)
    min_frac <- opts("min_frac_16s")
    total_asvs <- nrow(mtx)
    mapped_asvs <- length(unique(vsearch$hits))
    vs_tbl <- tibble::tibble(hits=vsearch$hits, targets=vsearch$targets) %>% 
	    dplyr::group_by(hits) %>%
	    dplyr::count(targets, name="n") %>%
	    dplyr::mutate(frac = n/sum(n)) %>%
	    dplyr::ungroup()
    vs_tbl_f <- vs_tbl %>%
        dplyr::group_by(hits) %>%
        dplyr::filter(frac >= min_frac) %>%
        dplyr::filter(dplyr::n() == 1) %>%
        dplyr::ungroup()
    retained_by_hit <- vs_tbl_f %>%
        dplyr::transmute(hits, retained_target=targets)
    decisions <- vs_tbl %>%
        dplyr::group_by(hits) %>%
        dplyr::summarise(
            n_retained_candidates=sum(frac >= min_frac),
            drop_reason=dplyr::case_when(
                n_retained_candidates == 1 ~ "retained",
                n_retained_candidates == 0 ~ "below_min_frac_16s",
                TRUE ~ "ambiguous_assignment"
            ),
            .groups="drop"
        ) %>%
        dplyr::left_join(retained_by_hit, by="hits")
    audit <- vs_tbl %>%
        dplyr::left_join(decisions, by="hits") %>%
        dplyr::transmute(
            asv_row=hits,
            asv_sequence=rownames(mtx)[hits],
            candidate_target=targets,
            assignment_count=n,
            assignment_fraction=frac,
            retained_target=retained_target,
            retained=!is.na(retained_target) & targets == retained_target,
            drop_reason=drop_reason
        )
    unmapped_hits <- setdiff(seq_len(total_asvs), unique(vs_tbl$hits))
    if (length(unmapped_hits) > 0) {
        audit <- dplyr::bind_rows(
            audit,
            tibble::tibble(
                asv_row=unmapped_hits,
                asv_sequence=rownames(mtx)[unmapped_hits],
                candidate_target=NA_character_,
                assignment_count=0L,
                assignment_fraction=0,
                retained_target=NA_character_,
                retained=FALSE,
                drop_reason="unmapped"
            )
        )
    }
    audit <- dplyr::arrange(audit, asv_row, candidate_target)
    rh <- vs_tbl_f$hits
    rt <- vs_tbl_f$targets
    subset.abd <- mtx[rh, , drop=FALSE]
    urt <- unique(rt)
    summed.uniq <- rowsum(as.matrix(subset.abd), group=rt, reorder=FALSE)
    out <- summed.uniq[urt, , drop=FALSE]
    attr(out, "phylogenize_16s_stats") <- list(
        total_asvs=total_asvs,
        mapped_asvs=mapped_asvs,
        retained_asvs=length(unique(rh)),
        dropped_asvs=total_asvs - length(unique(rh)),
        retained_species=nrow(out),
        total_abundance=sum(mtx),
        retained_abundance=sum(out)
    )
    attr(out, "phylogenize_16s_audit") <- audit
    out
}



#' Run AppSpam analysis on a FASTA file of sequences.
#'
#' Some particularly relevant options are:
#' \describe{
#'   \item{appspam_path}{String. Path to appspam binary.}
#'   \item{aln_path_16s}{String. Path to file containing aligned 16S sequences.}
#'   \item{tree_path_16s}{String. Path to tree for phylogenetic placement.}
#'   \item{named_asv_file}{String. Path to FASTA file containing named ASVs (Row1, ...).}
#'   \item{jplace_file}{String. Path giving where to store output .jplace file.}
#' }
#'
#' @return Returns TRUE unless an error is thrown.
#' @export run.appspam
run.appspam <- function(..., .opts=NULL) {
    opts <- resolve.16s.paths(..., .opts=.opts)
    appspam_path <- opts('appspam_path')
    if (appspam_path == "" || !(file.exists(appspam_path))) {
        pz.error(paste0("AppSpam executable not found: ", appspam_path),
                 .opts=opts)
    }
    if (file.access(appspam_path, mode=1) != 0) {
        pz.error(paste0("AppSpam executable is not runnable: ",
                        appspam_path),
                 .opts=opts)
    }
    aln_file <- opts('aln_path_16s')
    if (aln_file == "" || !(file.exists(aln_file))) {
        pz.error(paste0("16S alignment file not found: ", aln_file),
                 .opts=opts)
    }
    tree_file <- opts('tree_path_16s')
    if (tree_file == "" || !(file.exists(tree_file))) {
        pz.error(paste0("16S tree file not found: ", tree_file),
                 .opts=opts)
    }
    query_file <- opts('named_asv_file')
    if (query_file == "" || !(file.exists(query_file))) {
        pz.error(paste0("16S query FASTA not found: ", query_file),
                 .opts=opts)
    }
    jplace_file <- opts('jplace_file')
    if (jplace_file == "") {
        pz.error("jplace_file must be provided for AppSpam output",
                 .opts=opts)
    }
    jplace_dir <- dirname(jplace_file)
    if (!(dir.exists(jplace_dir))) {
        pz.error(paste0("AppSpam output directory not found: ", jplace_dir),
                 .opts=opts)
    }
    if (file.access(jplace_dir, mode=2) != 0) {
        pz.error(paste0("AppSpam output directory is not writable: ",
                        jplace_dir),
                 .opts=opts)
    }
    ncl <- suppressWarnings(as.numeric(opts('ncl')))
    if (is.na(ncl) || !is.finite(ncl) || ncl < 1 || ncl != as.integer(ncl)) {
        pz.error("ncl must be a positive integer for AppSpam",
                 .opts=opts)
    }
    appspam_args <- c(
            "-s", 
            aln_file,
            "-t",
            tree_file,
            "-q",
            query_file,
	    "--threads",
            ncl,
            "-o",
            jplace_file
    )
    run.external.tool(appspam_path,
                      appspam_args,
                      error_label="AppSpam",
                      .opts=opts)
}

#' Read in results from AppSpam
#'
#' Some particularly relevant options are:
#' \describe{
#'   \item{jplace_file}{String. Path giving where to store input .jplace file.}
#' }
#' @return List containing a vector of hits, a vector of MIDAS ID targets, and a
#'     data frame of the assignments as they came out of AppSpam 
#' @export
get.appspam.results <- function(..., .opts=NULL) {
    opts <- resolve.16s.paths(..., .opts=.opts)
    jplace_file <- opts('jplace_file')
    if (jplace_file == "") {
        pz.error("jplace_file must be provided for jplace input", .opts=opts)
    }
    if (!(file.exists(jplace_file))) {
        pz.error(paste0("jplace file not found: ", jplace_file), .opts=opts)
    }
    if (file.access(jplace_file, mode=4) != 0) {
        pz.error(paste0("jplace file is not readable: ", jplace_file),
                 .opts=opts)
    }
    if (file.info(jplace_file)$size == 0) {
        pz.error(paste0("jplace file was empty: ", jplace_file), .opts=opts)
    }
    # map to MIDAS IDs using vsearch
    placements <- treeio::read.jplace(jplace_file)
    tr <- treeio::get.tree(placements)
    pl <- treeio::get.placements(placements)
    edge <- tibble::tibble(V1=tr$edge[, 1], V2=tr$edge[, 2]) %>%
        dplyr::mutate(edge_num=row_number()) %>%
        dplyr::inner_join(., pl, by="edge_num")
    get_tips <- function(.x, tr) {
        tr$tip.label[tidytree::offspring(tr, .x, type="tips")]
    }
    if (opts('ncl') == 1) {
        tidy_tips <- lapply(edge$V1, get_tips, tr)
    } else {
        cl <- parallel::makeCluster(opts('ncl'))
        on.exit(parallel::stopCluster(cl), add=TRUE)
        tidy_tips <- parallel::parLapply(cl, edge$V1, get_tips, tr)
    }
    #tidy_tips <- purrr::map(edge$V1, ~ {
    #    tr$tip.label[tidytree::offspring(tr, .x, type="tips")]
    #}, .progress=TRUE)
    name_to_species <- dplyr::mutate(edge, tips_under = tidy_tips) %>%
	tidyr::unnest(tips_under) %>%
        tidyr::separate_wider_delim(
            tips_under,
            delim="____",
            names=c("gene","genus","species"))
    uniq_n2s <- name_to_species %>% select(name, species) %>% distinct() %>%
	    mutate(name = as.numeric(gsub("Row","", name)))
    return(list(hits=uniq_n2s$name,
                targets=uniq_n2s$species,
                assn=name_to_species))
}
