
#--- Process 16S data---#

#' Prepare input file for alignment
#'
#' \code{prepare.vsearch.input} outputs a FASTA file of the sequences in the
#' input 16S data for analysis using vsearch or vsearch.
#'
#' Some particularly relevant global options are:
#' \describe{
#'   \item{named_asv_file}{String. File name of the sequences written to disk
#'   and then read into vsearch/vsearch.}
#' }
#'
#' @param mtx A presence/absence or abundance matrix, with row names equal to
#'   amplicon sequence variant DNA sequences.
#' @export
prepare.vsearch.input <- function(mtx, ...) {
    opts <- clone_and_merge(PZ_OPTIONS, ...)
    binary = basename(opts('vsearch_dir'))
    check.dna <- is.dna(rownames(mtx))
    if (!(all(check.dna))) {
        pz.error(paste0(
            "Rownames in 16S data must correspond to the actual sequences of ", 
            "denoised amplicon sequence variants, but some rownames contained ",
            "invalid characters ",
            "(e.g. ", rownames(mtx)[which(!check.dna)[1]], ")."))
    }
    asvnames = paste0("Row", (1:nrow(mtx)))
    asvs = rownames(mtx)
    seqinr::write.fasta(as.list(asvs),
                        asvnames,
                        file.out=opts('named_asv_file'),
                        nbchar=99999,
                        as.string=TRUE)
    return(TRUE)
}

#' Run vsearch analysis on a FASTA file of sequences.
#'
#' \code{run.vsearch} runs, by default, the optimal sequence aligner vsearch
#' (doi.org/10.5281/zenodo.806850) on a FASTA file, typically one generated by
#' \code{prepare.vsearch.input}. By changing the \code{vsearch_dir} option, the
#' aligner vsearch can also be used. If the provided binary name is
#' not"vsearch", \emph{phylogenize} will assume an old version of vsearch is
#' being called that doesn't have the ability to search both strands.
#'
#' Some particularly relevant global options are:
#' \describe{
#'   \item{named_asv_file}{String. File name of the sequences to be read into
#' vsearch.}
#'   \item{vsearch_outfile}{String. File name where vsearch writes output
#'   which is then read back into \emph{phylogenize}.}
#'   \item{vsearch_dir}{String. Path where the binary of vsearch is found.}
#'   \item{vsearch_cutoff}{Float. Between 0.95 and 1.00; percent identity
#'   minimum for alignment results.}
#'   \item{vsearch_16sfile}{String. Path to the 16S FASTA database that maps
#'   back to MIDAS species.}
#'   \item{data_dir}{String. Path to directory containing the data files
#' required to perform a \emph{phylogenize} analysis. }
#' }
#'
#' @return Returns TRUE unless an error is thrown.
#' @export run.vsearch
run.vsearch <- function(...) {
    opts <- clone_and_merge(PZ_OPTIONS, ...)
    binary = basename(opts('vsearch_dir'))
    pid = opts('vsearch_cutoff')
    vsearch_args = c("--db",
		     file.path(opts('data_dir'),
			       opts('vsearch_16sfile')),
		     "--usearch_global",
		     opts('named_asv_file'),
		     "--strand both",
		     "--id",
		     pid,
		     "--maxaccepts",
		     20,
		     "--blast6out",
		     opts('vsearch_outfile'))
    pz.message(paste0("Calling aligner ", binary, " with arguments: ",
                      paste(vsearch_args, sep=" ", collapse=" ")))
    r <- system2(opts('vsearch_dir'),
                 args = vsearch_args)
    if (r != 0) {
        pz.error(paste0("Aligner failed with error code ", r))
    }
    return(TRUE)
}

#' Read in results from vsearch.
#'
#' \code{get.vsearch.results} reads and parses the output of vsearch to get the
#' best-hit MIDAS species identifier for any 16S hit. Note that the reference
#' 16S FASTA database file must describe entries in the format: ">gene;;
#' species_or_genus_ID;;MIDAS_ID". Only MIDAS_ID is used so the contents of
#' "gene" and "species_or_genus_ID" can be arbitrary.
#'
#' Some particularly relevant global options are:
#' \describe{
#'   \item{vsearch_outfile}{String. File name where vsearch writes output
#'   which is then read back into \emph{phylogenize}.}
#' }
#'
#' @return List containing a vector of hits, a vector of MIDAS ID targets, and a
#'     data frame of the assignments as they came out of vsearch.
#' @export
get.vsearch.results <- function(...) {
    opts <- clone_and_merge(PZ_OPTIONS, ...)
    # map to MIDAS IDs using vsearch (note X1 is query name, X3 is pctid)
    assignments <- 
        readr::read_tsv(opts('vsearch_outfile'), col_names=FALSE) %>%
	dplyr::group_by(X1) %>%
        dplyr::slice_max(X3) %>%
	dplyr::ungroup()
    row.hits <- as.numeric(gsub("Row", "", assignments[[1]]))
    row.targets <- sapply(assignments[[2]],
                          function(x) strsplit(x, ";;")[[1]][3])
    return(list(hits=row.hits, targets=row.targets, assn=assignments))
}

#' Sum non-unique rows after vsearch mapping.
#'
#' \code{sum.nonunique.vsearch} takes vsearch results and an abundance or
#' presence/absence matrix, drops any rows that mapped to multiple MIDAS IDs
#' (i.e. that couldn't confidently be assigned to a MIDAS species),
#' then sums any rows that mapped to the same MIDAS ID.
#'
#' Some particularly relevant global options are:
#' \describe{
#'   \item{min_frac_16s}{Numeric. Should be between 0.5 and 1. Only keep ASVs
#'   where at least this fraction of assignments are to the same species. 
#'   Allows some tolerance for mislabeled or phylogenetically-inconsistent
#'   16S sequences in the database. Default: 0.8}
#'   \item{out_dir}{String. Path to output directory. Default: "output"}
#'   \item{data_dir}{String. Path to directory containing the data files
#'   required to perform a \emph{phylogenize} analysis. Default: on package
#'   load, this default is set to the result of \code{system.file("extdata",
#'   package="phylogenize")}.}
#' }
#'
#' @param vsearch A list obtained by running \code{get.vsearch.results}.
#' @param mtx A presence/absence or abundance matrix, with row names equal to
#'     amplicon sequence variant DNA sequences.
#' @return A new matrix with MIDAS IDs as rows.
#' @export sum.nonunique.vsearch
sum.nonunique.vsearch <- function(vsearch, mtx, ...) {
    opts <- clone_and_merge(PZ_OPTIONS, ...)
    min_frac <- opts("min_frac_16s")
    vs_tbl <- tibble::tibble(hits=vsearch$hits, targets=vsearch$targets) %>% 
	    dplyr::group_by(hits) %>%
	    dplyr::count(targets, name="n") %>%
	    dplyr::mutate(frac = n/sum(n)) %>%
	    dplyr::ungroup()
    vs_tbl_f <- dplyr::filter(vs_tbl, frac >= min_frac)
    rh <- vs_tbl_f$hits
    rt <- vs_tbl_f$targets
    subset.abd <- mtx[rh, , drop=FALSE]
    urt <- unique(rt)
    summed.uniq <- t(sapply(urt, function(r) {
        w <- which(rt == r)
        apply(subset.abd[w, , drop=FALSE], 2, sum)
    }))
    rownames(summed.uniq) <- urt
    summed.uniq
}



#' Run AppSpam analysis on a FASTA file of sequences.
#'
#' Some particularly relevant global options are:
#' \describe{
#'   \item{appspam_path}{String. Path to appspam binary.}
#'   \item{aln_path_16s}{String. Path to file containing aligned 16S sequences.}
#'   \item{tree_path_16s}{String. Path to tree for phylogenetic placement.}
#'   minimum for alignment results.}
#'   \item{named_asv_file}{String. Path to FASTA file containing named ASVs (Row1, ...).}
#'   \item{jplace_file}{String. Path giving where to store output .jplace file.}
#' }
#'
#' @return Returns TRUE unless an error is thrown.
#' @export run.vsearch
run.appspam <- function(...) {
    opts <- clone_and_merge(PZ_OPTIONS, ...)
    r <- system2(
        opts('appspam_path'), 
        args = c(
            "-s", 
            opts('aln_path_16s'),
            "-t",
            opts('tree_path_16s'),
            "-q",
            opts('named_asv_file'),
	    "--threads",
            opts('ncl'),
            "-o",
            opts('jplace_file') # in setup should check if exists
        )
    )
    if (r != 0) {
        pz.error(paste0("AppSpam failed with error code ", r))
    }
    return(TRUE)
}

#' Read in results from AppSpam
#'
#' Some particularly relevant global options are:
#' \describe{
#'   \item{jplace_file}{String. Path giving where to store input .jplace file.}
#' }
#' @return List containing a vector of hits, a vector of MIDAS ID targets, and a
#'     data frame of the assignments as they came out of AppSpam 
#' @export
get.appspam.results <- function(...) {
    opts <- clone_and_merge(PZ_OPTIONS, ...)
    # map to MIDAS IDs using vsearch
    placements <- treeio::read.jplace(opts('jplace_file'))
    tr <- treeio::get.tree(placements)
    pl <- treeio::get.placements(placements)
    edge <- tibble::as_tibble(tr$edge) %>%
        dplyr::mutate(edge_num=row_number()) %>%
        dplyr::inner_join(., pl)
    cl <- parallel::makeCluster(opts('ncl'))
    tidy_tips <- parallel::parLapply(cl, edge$V1, \(.x, tr) {
        tr$tip.label[tidytree::offspring(tr, .x, type="tips")]
    }, tr)
    parallel::stopCluster(cl)
    #tidy_tips <- purrr::map(edge$V1, ~ {
    #    tr$tip.label[tidytree::offspring(tr, .x, type="tips")]
    #}, .progress=TRUE)
    name_to_species <- dplyr::mutate(edge, tips_under = tidy_tips) %>%
	tidyr::unnest(tips_under) %>%
        tidyr::separate_wider_delim(
            tips_under,
            delim="____",
            names=c("gene","genus","species"))
    uniq_n2s <- name_to_species %>% select(name, species) %>% distinct() %>%
	    mutate(name = as.numeric(gsub("Row","", name)))
    return(list(hits=uniq_n2s$name,
                targets=uniq_n2s$species,
                assn=name_to_species))
}
